name: ${project.name}
version: ${project.version}
main: com.saveapis.inventoryplugin.InventoryPlugin
api-version: 1.20
authors:
  - SaveFeelix
database: false
load: STARTUP
website: https://github.com/SaveFeelix/PexyFNA-InventoryPlugin

commands:
  inventory:
    description: Öffnet das Inventar. Für das Inventar wird eine Berechtigung benötigt! Diese kann in der config.yml geändert werden.
    usage: /<command>