# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - development
    paths-ignore:
      - .github/**
  pull_request:
    branches:
      - development
    paths-ignore:
      - .github/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 19
      - name: Maven Build
        run: mvn -B package --file pom.xml
      - name: List Files
        run: ls -la target/
